### ISSUE TITLE
Gale Moans don't shift to the later banks

### ISSUE THREAD

**Issue by Yungdeag** [bunfan/beat-banger-public#125]
### Issue Description

Gale only plays her quick_moans, never used her open_mouth_moans.

### OS

Windows

### Version

3.3

**Comment by Stefan-Mitric** [comment]
@komdog, you forgot to put timestamps for the Voice_paths in the Gales level. Every other level has it.

**Comment by hackerTiger21** [comment]
Still present in 3.455, but I decided to go ahead and "mod" these moans in to Gale's `keyframes.cfg` myself, and I'm pretty sure I know why they're currently unused. With the current frequency of voice triggers in Gale's charts, especially in the later sections, the `open_moan` sounds overlap due to being significantly longer than the `quick_moan` sounds. Therefore, in addition to adding the `open_moan` sounds into Gale's voice bank, you'd also need to space out the `"trigger_voice": true` flags in the `notes.cfg` file for all three difficulties whenever those longer moans become active.

**Comment by 1MPexe** [comment]
Gale's moans have been fixed in our most recent update.
