### ISSUE TITLE
Bug: Odd crashes during full-screen.

### ISSUE THREAD

**Issue by Mammon-Prince-Of-Hell** [bunfan/beat-banger-public#140]
### Discord Tag

@.undeadforlife

### Issue Description

Sometimes, when retrying the same level a bunch in a row, or just playing a bunch of levels in quick succession, or even just following the story in full-screen, it'll crash with no fanfare, usually during a loading screen.

### OS

Windows

### Version

3.3

**Comment by MikeT137** [comment]
I got the same crashing after i played Normal Claire.
Thankfully at least my new score was saved. But still it was surprising

**Comment by hackerTiger21** [comment]
Just happened to me, first time playing since new update so my save file was erased. Played through all levels on Normal, game crashed at the end of Claire's level instead of showing the "Under Construction" splash screen. Relaunching the game showed that my score was saved for the level. This crash doesn't happen on Virgin difficulty, expected behavior is exhibited there.

**Comment by 1MPexe** [comment]
Is this issue still occurring?

**Comment by hackerTiger21** [comment]
> Is this issue still occurring?

Have not encountered since, only on first playthrough.

**Comment by 1MPexe** [comment]
Glad to hear it!
