### ISSUE TITLE
No Handsfree Mods

### ISSUE THREAD

**Issue by Tusk102** [bunfan/beat-banger-public#235]
### Discord Tag

Tusk102

### Issue Description

As the title says. The new update does not allow handsfree mode after completing a mod, as well as not being able to see my prior scores.

### OS

Windows

### Version

3.34 dev1 (Steam)

**Comment by Stefan-Mitric** [comment]
I've encountered the same issue regarding the score display for levels that do not have any defined difficulties. Specifically, if a level is configured without any difficulty settings, the score fails to display at all. Instead of showing difficulties + the score, the game directly initiates the level. This behavior suggests that the score display mechanism is somehow tied to the presence of difficulty settings. It would be beneficial to ensure that scores can still be displayed or handled appropriately, even for levels without defined difficulty levels.

Here is an video proof for the Score and the [No Handsfree] not showing up.

https://github.com/bunfan/beat-banger-public/assets/146543675/f8608933-4731-456a-adc3-addd25a7d203

**Comment by Stefan-Mitric** [comment]
fixed in Version 3.454 (Hotfix)
