### ISSUE TITLE
Invisible notes

### ISSUE THREAD

**Issue by MagnusHan** [bunfan/beat-banger-public#308]
### Issue Description

c notes are invisible on highest difficulty levels. 

### OS

Windows

### Version

3.49

### Modifiers Enabled?

No Fail was active 

### What level or section is the scene present.

seems to happen halfway through the levels on highest difficulty

**Comment by Kapioga** [comment]
Hello! 
I just did some testing on the expert levels with the modifiers provided, these invisible notes are intentional and were included to increase the difficulty of expert levels. We understand there may be some confusion with this charting layout so we will do our best to make these adjustments more user-friendly.

Thank you!
