### ISSUE TITLE
Game Closing during play

### ISSUE THREAD

**Issue by CyrilTheOtt** [bunfan/beat-banger-public#384]
### Discord Tag

@cyriltheott

### Issue Description

When in play it seems when i hold down to do a long note and there is another long note right after and while im still holding down the last ones key and attempt to do the other the game forcibly closes.

### OS

Windows

### Version

3.7

### Modifiers Enabled?

N/A

### What level or section is the scene present.

All gameplay with to long notes after one another

**Comment by Znookey** [comment]
Instead of starting a new report I'll just add my observations to this one as I have the same issue:

The crash occurs most often during the third scene of  Cathy(Virgin Newbie). Specifically when long D and W beats arrive. The game will crash if I hold two buttons down at once while changing notes. Specifically when I finish the first long D-note and switch to the long W-note. 

This can also occur elsewhere in the song when other long notes begin. As long as two buttons are held for a split second as you swap notes and the notes are close enough together.

If I end the preceding notes early such that I never have two buttons pressed at the same time then it does not crash.

**Comment by CyrilTheOtt** [comment]
Adding to this after some more testing it even occurs when going from long note to short which leads me to believe its moreso about holding down to buttons

**Comment by Stefan-Mitric** [comment]
Duplicate #349
