### ISSUE TITLE
Can't go back to title when mid-game

### ISSUE THREAD

**Issue by CheeseMuncherTM** [bunfan/beat-banger-public#62]
**Describe the bug**
you cant go back to title screen 90% of the time when mid-game

**To Reproduce**
1. play any level
2. Click on esc
3. Scroll down to exit to title

**Expected behavior**
it's supposed to go back to title but it doesn't

**Screenshots**

**Additional context**
doesn't work with both z and enter

**Comment by K3fka** [comment]
I've identified some general issues with the pause menu relating to scrolling. Scrolling up from the top option appears to wrap around to the bottom as expected, but none of the menu options can be interacted with if you do this. If you continue scrolling up and attempt to wrap around a second time, the selection disappears. This also happens if you attempt to wrap from the bottom back to the top.
![image](https://user-images.githubusercontent.com/1146957/125821400-625c96ab-85ad-4e7c-a383-1bbf165575ae.png)

**Comment by komdog** [comment]
Fixed in 1.3
