### ISSUE TITLE
Background rework

### ISSUE THREAD

**Issue by MikeT137** [bunfan/beat-banger-public#7]
**Describe the feature you'd like**
So, i personally love how the game looks, but one issue im having is that when im playing for a bit, the background has this wibbly wobbly kind of movement that, messes with my vision. When i look away after playing, my vision is moving just like the background. The effect doesnt last too long but, id still love something to change about that.

And, im asking for, either the background to be a simple color, or the checkered pattern to be static and/or move in one direction (diagonally to the upper left for example) without any additional squishing, stretching, warping or any other weird movement.
Thanks for reading <3

**Comment by komdog** [comment]
While the background does wobble a bit, after playing and testing the game for the last two years, I haven't noticed any optical illusion due to looking at the background. However, I have experienced the same effect when staring at the movement of the notes for a prolonged time.

Could you run a level without the notes on the screen by turning on the hide HUD modifier and let me know if you still experience the same optical illusion?

**Comment by komdog** [comment]
Closed
